#!/usr/bin/env python
# vim:fileencoding=UTF-8:ts=2:sw=2:sta:et:sts=2:ai

from .r_fantasy_top_novels_2025 import UrlFetcherRFantasyTopNovels2025
from .r_fantasy_top_self_published_novels_2024 import (
  UrlFetcherRFantasyTopSelfPublishedNovels2024,
)
from .r_fantasy_top_standalone_novels_2024 import (
  UrlFetcherRFantasyTopStandaloneNovels2024,
)
from .anthony import (
  UrlFetcherAnthonyAnthologyCollection,
  UrlFetcherAnthonyChildrensYA,
  UrlFetcherAnthonyCozyHumorousMystery,
  UrlFetcherAnthonyCriticalNonfictionWork,
  UrlFetcherAnthonyFirstMystery,
  UrlFetcherAnthonyHistoricalMystery,
  UrlFetcherAnthonyMysteryNovel,
  UrlFetcherAnthonyPaperbackEBookAudiobook,
  UrlFetcherAnthonyParanormalMystery,
)
from .agatha import (
  UrlFetcherAgathaAward,
  UrlFetcherAgathaBestNovel,
  UrlFetcherAgathaChildrensYA,
  UrlFetcherAgathaFirstNovel,
  UrlFetcherAgathaHistoricalNovel,
  UrlFetcherAgathaNonFiction,
)
from .macavity import (
  UrlFetcherMacavityAward,
  UrlFetcherMacavityFirstMystery,
  UrlFetcherMacavityHistoricalMystery,
  UrlFetcherMacavityMysteryNovel,
  UrlFetcherMacavityNonfictionCritical,
)
from .shamus import (
  UrlFetcherShamusFirstPINovel,
  UrlFetcherShamusPaperbackOriginal,
  UrlFetcherShamusPINovel,
)
from .barry import (
  UrlFetcherBarryBritishCrimeNovel,
  UrlFetcherBarryFirstMysteryNovel,
  UrlFetcherBarryMysteryNovel,
  UrlFetcherBarryPaperbackOriginal,
  UrlFetcherBarryThriller,
)
from .lefty import (
  UrlFetcherLeftyDebutMysteryNovel,
  UrlFetcherLeftyHistoricalMysteryNovel,
  UrlFetcherLeftyHumorousMysteryNovel,
  UrlFetcherLeftyMysteryNovel,
)
from .crime_writers_canada import (
  UrlFetcherCrimeWritersOfCanadaFirstNovel,
  UrlFetcherCrimeWritersOfCanadaFrenchCrimeBook,
  UrlFetcherCrimeWritersOfCanadaJuvenileYA,
  UrlFetcherCrimeWritersOfCanadaNonfiction,
  UrlFetcherCrimeWritersOfCanadaNovel,
)
from .davitt import (
  UrlFetcherDavittAdultNovel,
  UrlFetcherDavittChildrensNovel,
  UrlFetcherDavittDebutNovel,
  UrlFetcherDavittNonFiction,
  UrlFetcherDavittYoungAdultNovel,
)
from .dilys import UrlFetcherDilysAward
from .gumshoe import (
  UrlFetcherGumshoeEuropeanCrimeNovel,
  UrlFetcherGumshoeFirstNovel,
  UrlFetcherGumshoeMystery,
  UrlFetcherGumshoeThriller,
)
from .ned_kelly import (
  UrlFetcherNedKellyCrimeFiction,
  UrlFetcherNedKellyDebutCrimeFiction,
  UrlFetcherNedKellyInternationalCrimeFiction,
  UrlFetcherNedKellyTrueCrime,
)
from .ngaio_marsh import (
  UrlFetcherNgaioMarshCrimeNovel,
  UrlFetcherNgaioMarshFirstNovel,
  UrlFetcherNgaioMarshNonFiction,
  UrlFetcherNgaioMarshYoungerReaders,
)
from .theakston import UrlFetcherTheakstonOldPeculierCrimeNovelOfTheYear
from .seiun import UrlFetcherSeiunTranslatedNovel
from .seiun import (
  UrlFetcherSeiunComic,
  UrlFetcherSeiunJapaneseLongWork,
  UrlFetcherSeiunNonfiction,
)
from .sword_and_laser import UrlFetcherSwordAndLaser
from .aurora import (
  UrlFetcherAuroraGraphicNovel,
  UrlFetcherAuroraNoveletteNovella,
  UrlFetcherAuroraNovel,
  UrlFetcherAuroraRelatedWork,
  UrlFetcherAuroraYANovel,
)
from .aurealis import (
  UrlFetcherAurealisAnthology,
  UrlFetcherAurealisChildrens812IllustratedWorkPictureBook,
  UrlFetcherAurealisChildrens812LongFiction,
  UrlFetcherAurealisChildrensBook,
  UrlFetcherAurealisChildrensFiction,
  UrlFetcherAurealisChildrensFictionPictures,
  UrlFetcherAurealisChildrensFictionWords,
  UrlFetcherAurealisCollection,
  UrlFetcherAurealisFantasyNovel,
  UrlFetcherAurealisFantasyNovella,
  UrlFetcherAurealisGoldenAurealisNovel,
  UrlFetcherAurealisGraphicNovelIllustratedWork,
  UrlFetcherAurealisHorrorNovel,
  UrlFetcherAurealisHorrorNovella,
  UrlFetcherAurealisSaraDouglassBookSeries,
  UrlFetcherAurealisSFNovel,
  UrlFetcherAurealisSFNovella,
  UrlFetcherAurealisYoungAdultNovel,
)
from .bram_stoker import (
  UrlFetcherBramStokerAnthology,
  UrlFetcherBramStokerFictionCollection,
  UrlFetcherBramStokerFirstNovel,
  UrlFetcherBramStokerLongFiction,
  UrlFetcherBramStokerMiddleGradeNovel,
  UrlFetcherBramStokerNonfiction,
  UrlFetcherBramStokerNovel,
  UrlFetcherBramStokerGraphicNovel,
  UrlFetcherBramStokerPoetryCollection,
  UrlFetcherBramStokerYoungAdultNovel,
)
from .bsfa import (
  UrlFetcherBSFACollectionAnthology,
  UrlFetcherBSFAFictionForYoungerReaders,
  UrlFetcherBSFALongNonfiction,
  UrlFetcherBSFANovel,
  UrlFetcherBSFAShorterFiction,
)
from .clarke import UrlFetcherArthurCClarkeAwardNovel
from .cwa import (
  UrlFetcherCWACrimeFictionInTranslationDagger,
  UrlFetcherCWAGoldDagger,
  UrlFetcherCWAHistoricalDagger,
  UrlFetcherCWAIanFlemingSteelDagger,
)
from .edgar import (
  UrlFetcherEdgarCriticalBiographicalWork,
  UrlFetcherEdgarFactCrime,
  UrlFetcherEdgarFirstNovel,
  UrlFetcherEdgarJuvenile,
  UrlFetcherEdgarLilianJacksonBraunAward,
  UrlFetcherEdgarMaryHigginsClarkAward,
  UrlFetcherEdgarNovel,
  UrlFetcherEdgarPaperbackOriginal,
  UrlFetcherEdgarYoungAdult,
)
from .itw import (
  UrlFetcherITWBestAudiobook,
  UrlFetcherITWBestEBookOriginalNovel,
  UrlFetcherITWBestFirstNovel,
  UrlFetcherITWBestHardcoverNovel,
  UrlFetcherITWBestPaperbackOriginalNovel,
  UrlFetcherITWBestSeriesNovel,
  UrlFetcherITWBestStandaloneMysteryNovel,
  UrlFetcherITWBestStandaloneThrillerNovel,
  UrlFetcherITWBestYoungAdultNovel,
)
from .ditmar import (
  UrlFetcherDitmarCollectedWork,
  UrlFetcherDitmarNovel,
  UrlFetcherDitmarNovellaNovelette,
)
from .hugo import (
  UrlFetcherHugoAwardsGraphicStory,
  UrlFetcherHugoAwardsNovel,
  UrlFetcherHugoAwardsNovella,
  UrlFetcherHugoAwardsRelatedWork,
  UrlFetcherHugoAwardsSeries,
  UrlFetcherLodestarAward,
)
from .locus import (
  UrlFetcherLocusAllTime1975Novel,
  UrlFetcherLocusAllTime1987FantasyNovel,
  UrlFetcherLocusAllTime1987SFNovel,
  UrlFetcherLocusAllTime1998FantasyNovel,
  UrlFetcherLocusAllTime1998SFNovel,
  UrlFetcherLocusAllTime2012FH20thNovel,
  UrlFetcherLocusAllTime2012FH21stNovel,
  UrlFetcherLocusAllTime2012SF20thNovel,
  UrlFetcherLocusAllTime2012SF21stNovel,
  UrlFetcherLocusAnnualFantasyNovel,
  UrlFetcherLocusAnnualFirstNovel,
  UrlFetcherLocusAnnualHorrorNovel,
  UrlFetcherLocusAnnualAnthology,
  UrlFetcherLocusAnnualCollection,
  UrlFetcherLocusAnnualIllustratedAndArtBook,
  UrlFetcherLocusAnnualNonfiction,
  UrlFetcherLocusAnnualNovella,
  UrlFetcherLocusAnnualSFNovel,
  UrlFetcherLocusAnnualTranslatedNovel,
  UrlFetcherLocusAnnualYoungAdultNovel,
)
from .mythopoeic import (
  UrlFetcherMythopoeicAdultLiterature,
  UrlFetcherMythopoeicChildrensLiterature,
  UrlFetcherMythopoeicFantasy,
  UrlFetcherMythopoeicYoungAdultLiterature,
)
from .nebula import (
  UrlFetcherNebulaAndreNorton,
  UrlFetcherNebulaAwardsComics,
  UrlFetcherNebulaAwardsNovel,
  UrlFetcherNebulaAwardsNovella,
)
from .nommo import (
  UrlFetcherNommoGraphicNovel,
  UrlFetcherNommoNovel,
  UrlFetcherNommoNovella,
)
from .otherwise_tiptree import UrlFetcherOtherwiseTiptreeBooksAndSeries
from .philip_k_dick import UrlFetcherPhilipKDickAwardNovel
from .prometheus import (
  UrlFetcherPrometheusHallOfFame,
  UrlFetcherPrometheusNovel,
  UrlFetcherPrometheusSpecialAwards,
  UrlFetcherPrometheusYoungAdultHonorRoll,
)
from .shirley_jackson import (
  UrlFetcherShirleyJacksonEditedAnthology,
  UrlFetcherShirleyJacksonNovel,
  UrlFetcherShirleyJacksonNovella,
  UrlFetcherShirleyJacksonSingleAuthorCollection,
)
from .spsfc import UrlFetcherSPSFCNovelFinalists
from .world_fantasy import (
  UrlFetcherWorldFantasyAnthology,
  UrlFetcherWorldFantasyCollection,
  UrlFetcherWorldFantasyCollectionAnthology,
  UrlFetcherWorldFantasyNovel,
  UrlFetcherWorldFantasyNovella,
)


URL_FETCHER_CLASSES = (
  UrlFetcherRFantasyTopNovels2025,
  UrlFetcherRFantasyTopStandaloneNovels2024,
  UrlFetcherRFantasyTopSelfPublishedNovels2024,
  UrlFetcherSwordAndLaser,
  UrlFetcherHugoAwardsNovel,
  UrlFetcherHugoAwardsNovella,
  UrlFetcherHugoAwardsSeries,
  UrlFetcherHugoAwardsGraphicStory,
  UrlFetcherHugoAwardsRelatedWork,
  UrlFetcherLodestarAward,
  UrlFetcherNebulaAwardsNovel,
  UrlFetcherNebulaAwardsNovella,
  UrlFetcherNebulaAndreNorton,
  UrlFetcherNebulaAwardsComics,
  UrlFetcherLocusAnnualSFNovel,
  UrlFetcherLocusAnnualFantasyNovel,
  UrlFetcherLocusAnnualHorrorNovel,
  UrlFetcherLocusAnnualYoungAdultNovel,
  UrlFetcherLocusAnnualFirstNovel,
  UrlFetcherLocusAnnualTranslatedNovel,
  UrlFetcherLocusAnnualNovella,
  UrlFetcherLocusAnnualAnthology,
  UrlFetcherLocusAnnualCollection,
  UrlFetcherLocusAnnualNonfiction,
  UrlFetcherLocusAnnualIllustratedAndArtBook,
  UrlFetcherLocusAllTime1975Novel,
  UrlFetcherLocusAllTime1987SFNovel,
  UrlFetcherLocusAllTime1987FantasyNovel,
  UrlFetcherLocusAllTime1998SFNovel,
  UrlFetcherLocusAllTime1998FantasyNovel,
  UrlFetcherLocusAllTime2012SF20thNovel,
  UrlFetcherLocusAllTime2012FH20thNovel,
  UrlFetcherLocusAllTime2012SF21stNovel,
  UrlFetcherLocusAllTime2012FH21stNovel,
  UrlFetcherWorldFantasyNovel,
  UrlFetcherWorldFantasyNovella,
  UrlFetcherWorldFantasyAnthology,
  UrlFetcherWorldFantasyCollection,
  UrlFetcherWorldFantasyCollectionAnthology,
  UrlFetcherArthurCClarkeAwardNovel,
  UrlFetcherBSFANovel,
  UrlFetcherBSFAShorterFiction,
  UrlFetcherBSFACollectionAnthology,
  UrlFetcherBSFAFictionForYoungerReaders,
  UrlFetcherBSFALongNonfiction,
  UrlFetcherPhilipKDickAwardNovel,
  UrlFetcherMythopoeicFantasy,
  UrlFetcherMythopoeicAdultLiterature,
  UrlFetcherMythopoeicYoungAdultLiterature,
  UrlFetcherMythopoeicChildrensLiterature,
  UrlFetcherBramStokerNovel,
  UrlFetcherBramStokerFirstNovel,
  UrlFetcherBramStokerYoungAdultNovel,
  UrlFetcherBramStokerMiddleGradeNovel,
  UrlFetcherBramStokerLongFiction,
  UrlFetcherBramStokerFictionCollection,
  UrlFetcherBramStokerAnthology,
  UrlFetcherBramStokerPoetryCollection,
  UrlFetcherBramStokerGraphicNovel,
  UrlFetcherBramStokerNonfiction,
  UrlFetcherShirleyJacksonNovel,
  UrlFetcherShirleyJacksonNovella,
  UrlFetcherShirleyJacksonSingleAuthorCollection,
  UrlFetcherShirleyJacksonEditedAnthology,
  UrlFetcherOtherwiseTiptreeBooksAndSeries,
  UrlFetcherPrometheusNovel,
  UrlFetcherPrometheusHallOfFame,
  UrlFetcherPrometheusYoungAdultHonorRoll,
  UrlFetcherPrometheusSpecialAwards,
  UrlFetcherAuroraNovel,
  UrlFetcherAuroraYANovel,
  UrlFetcherAuroraNoveletteNovella,
  UrlFetcherAuroraRelatedWork,
  UrlFetcherAuroraGraphicNovel,
  UrlFetcherAurealisSFNovel,
  UrlFetcherAurealisGoldenAurealisNovel,
  UrlFetcherAurealisFantasyNovel,
  UrlFetcherAurealisHorrorNovel,
  UrlFetcherAurealisSFNovella,
  UrlFetcherAurealisFantasyNovella,
  UrlFetcherAurealisHorrorNovella,
  UrlFetcherAurealisAnthology,
  UrlFetcherAurealisCollection,
  UrlFetcherAurealisGraphicNovelIllustratedWork,
  UrlFetcherAurealisYoungAdultNovel,
  UrlFetcherAurealisChildrensBook,
  UrlFetcherAurealisChildrensFiction,
  UrlFetcherAurealisChildrensFictionWords,
  UrlFetcherAurealisChildrensFictionPictures,
  UrlFetcherAurealisChildrens812LongFiction,
  UrlFetcherAurealisChildrens812IllustratedWorkPictureBook,
  UrlFetcherAurealisSaraDouglassBookSeries,
  UrlFetcherDitmarNovel,
  UrlFetcherDitmarNovellaNovelette,
  UrlFetcherDitmarCollectedWork,
  UrlFetcherSPSFCNovelFinalists,
  UrlFetcherSeiunTranslatedNovel,
  UrlFetcherSeiunJapaneseLongWork,
  UrlFetcherSeiunComic,
  UrlFetcherSeiunNonfiction,
  UrlFetcherNommoNovel,
  UrlFetcherNommoNovella,
  UrlFetcherNommoGraphicNovel,
  UrlFetcherEdgarNovel,
  UrlFetcherEdgarFirstNovel,
  UrlFetcherEdgarPaperbackOriginal,
  UrlFetcherEdgarFactCrime,
  UrlFetcherEdgarCriticalBiographicalWork,
  UrlFetcherEdgarJuvenile,
  UrlFetcherEdgarYoungAdult,
  UrlFetcherEdgarMaryHigginsClarkAward,
  UrlFetcherEdgarLilianJacksonBraunAward,
  UrlFetcherCWAGoldDagger,
  UrlFetcherCWAIanFlemingSteelDagger,
  UrlFetcherCWAHistoricalDagger,
  UrlFetcherCWACrimeFictionInTranslationDagger,
  UrlFetcherITWBestStandaloneThrillerNovel,
  UrlFetcherITWBestStandaloneMysteryNovel,
  UrlFetcherITWBestSeriesNovel,
  UrlFetcherITWBestFirstNovel,
  UrlFetcherITWBestYoungAdultNovel,
  UrlFetcherITWBestHardcoverNovel,
  UrlFetcherITWBestPaperbackOriginalNovel,
  UrlFetcherITWBestEBookOriginalNovel,
  UrlFetcherITWBestAudiobook,
  UrlFetcherAnthonyAnthologyCollection,
  UrlFetcherAgathaBestNovel,
  UrlFetcherAgathaFirstNovel,
  UrlFetcherAgathaHistoricalNovel,
  UrlFetcherAgathaNonFiction,
  UrlFetcherAgathaChildrensYA,
  UrlFetcherMacavityMysteryNovel,
  UrlFetcherMacavityFirstMystery,
  UrlFetcherMacavityHistoricalMystery,
  UrlFetcherMacavityNonfictionCritical,
  UrlFetcherShamusPINovel,
  UrlFetcherShamusPaperbackOriginal,
  UrlFetcherShamusFirstPINovel,
  UrlFetcherBarryMysteryNovel,
  UrlFetcherBarryFirstMysteryNovel,
  UrlFetcherBarryPaperbackOriginal,
  UrlFetcherBarryThriller,
  UrlFetcherBarryBritishCrimeNovel,
  UrlFetcherCrimeWritersOfCanadaNovel,
  UrlFetcherCrimeWritersOfCanadaFirstNovel,
  UrlFetcherCrimeWritersOfCanadaNonfiction,
  UrlFetcherCrimeWritersOfCanadaJuvenileYA,
  UrlFetcherCrimeWritersOfCanadaFrenchCrimeBook,
  UrlFetcherDavittAdultNovel,
  UrlFetcherDavittDebutNovel,
  UrlFetcherDavittNonFiction,
  UrlFetcherDavittYoungAdultNovel,
  UrlFetcherDavittChildrensNovel,
  UrlFetcherDilysAward,
  UrlFetcherGumshoeMystery,
  UrlFetcherGumshoeThriller,
  UrlFetcherGumshoeFirstNovel,
  UrlFetcherGumshoeEuropeanCrimeNovel,
  UrlFetcherLeftyHumorousMysteryNovel,
  UrlFetcherLeftyHistoricalMysteryNovel,
  UrlFetcherLeftyMysteryNovel,
  UrlFetcherLeftyDebutMysteryNovel,
  UrlFetcherNedKellyCrimeFiction,
  UrlFetcherNedKellyDebutCrimeFiction,
  UrlFetcherNedKellyTrueCrime,
  UrlFetcherNedKellyInternationalCrimeFiction,
  UrlFetcherNgaioMarshCrimeNovel,
  UrlFetcherNgaioMarshFirstNovel,
  UrlFetcherNgaioMarshNonFiction,
  UrlFetcherNgaioMarshYoungerReaders,
  UrlFetcherTheakstonOldPeculierCrimeNovelOfTheYear,
  UrlFetcherAnthonyChildrensYA,
  UrlFetcherAnthonyCozyHumorousMystery,
  UrlFetcherAnthonyCriticalNonfictionWork,
  UrlFetcherAnthonyFirstMystery,
  UrlFetcherAnthonyHistoricalMystery,
  UrlFetcherAnthonyMysteryNovel,
  UrlFetcherAnthonyPaperbackEBookAudiobook,
  UrlFetcherAnthonyParanormalMystery,
)


def available_url_fetchers():
  return tuple(fetcher_class() for fetcher_class in URL_FETCHER_CLASSES)
