#!/usr/bin/env python
# vim:fileencoding=UTF-8:ts=2:sw=2:sta:et:sts=2:ai

from .r_fantasy_top_novels_2025 import UrlFetcherRFantasyTopNovels2025
from .r_fantasy_top_self_published_novels_2024 import (
  UrlFetcherRFantasyTopSelfPublishedNovels2024,
)
from .r_fantasy_top_standalone_novels_2024 import (
  UrlFetcherRFantasyTopStandaloneNovels2024,
)
from .anthony import (
  UrlFetcherAnthonyAnthologyCollection,
  UrlFetcherAnthonyChildrensYA,
  UrlFetcherAnthonyCozyHumorousMystery,
  UrlFetcherAnthonyCriticalNonfictionWork,
  UrlFetcherAnthonyFirstMystery,
  UrlFetcherAnthonyHistoricalMystery,
  UrlFetcherAnthonyMysteryNovel,
  UrlFetcherAnthonyPaperbackEBookAudiobook,
  UrlFetcherAnthonyParanormalMystery,
)
from .agatha import (
  UrlFetcherAgathaAward,
  UrlFetcherAgathaBestNovel,
  UrlFetcherAgathaChildrensYA,
  UrlFetcherAgathaFirstNovel,
  UrlFetcherAgathaHistoricalNovel,
  UrlFetcherAgathaNonFiction,
)
from .macavity import (
  UrlFetcherMacavityAward,
  UrlFetcherMacavityFirstMystery,
  UrlFetcherMacavityHistoricalMystery,
  UrlFetcherMacavityMysteryNovel,
  UrlFetcherMacavityNonfictionCritical,
)
from .shamus import (
  UrlFetcherShamusFirstPINovel,
  UrlFetcherShamusPaperbackOriginal,
  UrlFetcherShamusPINovel,
)
from .barry import (
  UrlFetcherBarryBritishCrimeNovel,
  UrlFetcherBarryFirstMysteryNovel,
  UrlFetcherBarryMysteryNovel,
  UrlFetcherBarryPaperbackOriginal,
  UrlFetcherBarryThriller,
)
from .lefty import (
  UrlFetcherLeftyDebutMysteryNovel,
  UrlFetcherLeftyHistoricalMysteryNovel,
  UrlFetcherLeftyHumorousMysteryNovel,
  UrlFetcherLeftyMysteryNovel,
)
from .hammett import UrlFetcherHammettPrize
from .nero import UrlFetcherNeroAward
from .strand import (
  UrlFetcherStrandDebutMystery,
  UrlFetcherStrandMysteryNovel,
)
from .crime_writers_canada import (
  UrlFetcherCrimeWritersOfCanadaFirstNovel,
  UrlFetcherCrimeWritersOfCanadaFrenchCrimeBook,
  UrlFetcherCrimeWritersOfCanadaJuvenileYA,
  UrlFetcherCrimeWritersOfCanadaNonfiction,
  UrlFetcherCrimeWritersOfCanadaNovel,
)
from .davitt import (
  UrlFetcherDavittAdultNovel,
  UrlFetcherDavittChildrensNovel,
  UrlFetcherDavittDebutNovel,
  UrlFetcherDavittNonFiction,
  UrlFetcherDavittYoungAdultNovel,
)
from .dilys import UrlFetcherDilysAward
from .gumshoe import (
  UrlFetcherGumshoeEuropeanCrimeNovel,
  UrlFetcherGumshoeFirstNovel,
  UrlFetcherGumshoeMystery,
  UrlFetcherGumshoeThriller,
)
from .ned_kelly import (
  UrlFetcherNedKellyCrimeFiction,
  UrlFetcherNedKellyDebutCrimeFiction,
  UrlFetcherNedKellyInternationalCrimeFiction,
  UrlFetcherNedKellyTrueCrime,
)
from .ngaio_marsh import (
  UrlFetcherNgaioMarshCrimeNovel,
  UrlFetcherNgaioMarshFirstNovel,
  UrlFetcherNgaioMarshNonFiction,
  UrlFetcherNgaioMarshYoungerReaders,
)
from .theakston import UrlFetcherTheakstonOldPeculierCrimeNovelOfTheYear
from .pulitzer import (
  UrlFetcherPulitzerFiction,
  UrlFetcherPulitzerGeneralNonfiction,
)
from .national_book_award import (
  UrlFetcherNationalBookAwardFiction,
  UrlFetcherNationalBookAwardNonfiction,
  UrlFetcherNationalBookAwardYoungPeoplesLiterature,
)
from .baillie_gifford import UrlFetcherBaillieGiffordPrize
from .pen_america import (
  UrlFetcherPENDiamonsteinSpielvogelAward,
  UrlFetcherPENGalbraithAward,
  UrlFetcherPENJeanSteinBookAward,
  UrlFetcherPENOpenBookAward,
)
from .pen_faulkner_foundation import (
  UrlFetcherPENFaulknerAward,
  UrlFetcherPENHemingwayAward,
)
from .lukas import (
  UrlFetcherJAnthonyLukasBookPrize,
  UrlFetcherMarkLyntonHistoryPrize,
)
from .orwell import UrlFetcherOrwellPrizePoliticalWriting
from .andrew_carnegie import UrlFetcherAndrewCarnegieNonfiction
from .kirkus import (
  UrlFetcherKirkusPrizeFiction,
  UrlFetcherKirkusPrizeNonfiction,
  UrlFetcherKirkusPrizeYoungReadersLiterature,
)
from .womens_prize import (
  UrlFetcherWomensPrizeFiction,
  UrlFetcherWomensPrizeNonFiction,
)
from .royal_society import UrlFetcherRoyalSocietyScienceBookPrize
from .booker import (
  UrlFetcherBookerPrize,
  UrlFetcherInternationalBookerPrize,
)
from .governor_general import (
  UrlFetcherGovernorGeneralEnglishFiction,
  UrlFetcherGovernorGeneralEnglishNonfiction,
  UrlFetcherGovernorGeneralEnglishYoungPeoplesIllustratedBooks,
  UrlFetcherGovernorGeneralEnglishYoungPeoplesText,
  UrlFetcherGovernorGeneralFrenchYoungPeoplesIllustratedBooks,
  UrlFetcherGovernorGeneralFrenchYoungPeoplesText,
)
from .costa_whitbread import (
  UrlFetcherCostaWhitbreadBiography,
  UrlFetcherCostaWhitbreadBookOfTheYear,
  UrlFetcherCostaWhitbreadChildrensBook,
  UrlFetcherCostaWhitbreadFirstNovel,
  UrlFetcherCostaWhitbreadNovel,
)
from .giller import UrlFetcherGillerPrize
from .folio_writers_prize import (
  UrlFetcherFolioWritersPrizeBookOfTheYear,
  UrlFetcherFolioWritersPrizeFiction,
  UrlFetcherFolioWritersPrizeNonfiction,
)
from .goldsmiths import UrlFetcherGoldsmithsPrize
from .national_book_critics_circle import (
  UrlFetcherNationalBookCriticsCircleBiography,
  UrlFetcherNationalBookCriticsCircleCriticism,
  UrlFetcherNationalBookCriticsCircleFiction,
  UrlFetcherNationalBookCriticsCircleGreggBarriosTranslation,
  UrlFetcherNationalBookCriticsCircleJohnLeonard,
  UrlFetcherNationalBookCriticsCircleMemoirAutobiography,
  UrlFetcherNationalBookCriticsCircleNonfiction,
  UrlFetcherNationalBookCriticsCirclePoetry,
)
from .dublin_literary_award import UrlFetcherDublinLiteraryAward
from .center_for_fiction import UrlFetcherCenterForFictionFirstNovelPrize
from .walter_scott import UrlFetcherWalterScottPrize
from .james_tait_black import (
  UrlFetcherJamesTaitBlackBiography,
  UrlFetcherJamesTaitBlackFiction,
)
from .miles_franklin import UrlFetcherMilesFranklinLiteraryAward
from .nero_book_awards import (
  UrlFetcherNeroBookAwardsChildrensFiction,
  UrlFetcherNeroBookAwardsDebutFiction,
  UrlFetcherNeroBookAwardsFiction,
  UrlFetcherNeroBookAwardsGoldPrize,
  UrlFetcherNeroBookAwardsNonfiction,
)
from .nsw_premiers_literary_awards import (
  UrlFetcherNSWPremiersLiteraryAwardsBookOfTheYear,
  UrlFetcherNSWPremiersLiteraryAwardsChristinaSteadFiction,
  UrlFetcherNSWPremiersLiteraryAwardsDouglasStewartNonfiction,
  UrlFetcherNSWPremiersLiteraryAwardsEthelTurnerYoungPeople,
  UrlFetcherNSWPremiersLiteraryAwardsGlendaAdamsNewWriting,
  UrlFetcherNSWPremiersLiteraryAwardsIndigenousWriters,
  UrlFetcherNSWPremiersLiteraryAwardsMulticulturalNSW,
  UrlFetcherNSWPremiersLiteraryAwardsPatriciaWrightsonChildrens,
  UrlFetcherNSWPremiersLiteraryAwardsPeoplesChoice,
)
from .queensland_literary_awards import (
  UrlFetcherQueenslandLiteraryAwardsChildrens,
  UrlFetcherQueenslandLiteraryAwardsFiction,
  UrlFetcherQueenslandLiteraryAwardsNonfiction,
  UrlFetcherQueenslandLiteraryAwardsPeoplesChoice,
  UrlFetcherQueenslandLiteraryAwardsStateSignificance,
  UrlFetcherQueenslandLiteraryAwardsYoungAdult,
)
from .western_australian_premiers_book_awards import (
  UrlFetcherWesternAustralianPremiersBookAwardsBookOfTheYear,
  UrlFetcherWesternAustralianPremiersBookAwardsChildrens,
  UrlFetcherWesternAustralianPremiersBookAwardsEmergingWriter,
  UrlFetcherWesternAustralianPremiersBookAwardsFiction,
  UrlFetcherWesternAustralianPremiersBookAwardsNonfiction,
  UrlFetcherWesternAustralianPremiersBookAwardsYoungAdult,
)
from .south_australian_literary_awards import (
  UrlFetcherSouthAustralianLiteraryAwardsChildrens,
  UrlFetcherSouthAustralianLiteraryAwardsFiction,
  UrlFetcherSouthAustralianLiteraryAwardsNonfiction,
  UrlFetcherSouthAustralianLiteraryAwardsPremiersAward,
  UrlFetcherSouthAustralianLiteraryAwardsYoungAdult,
)
from .act_book_of_the_year import UrlFetcherACTBookOfTheYearAward
from .rwa_awards import UrlFetcherRWARITAAwards, UrlFetcherRWAVivianAwards
from .rna_awards import UrlFetcherRNAJoanHessayonAward, UrlFetcherRNARomanticNovelAwards
from .ripped_bodice_awards import UrlFetcherRippedBodiceAwards
from .romantic_times_awards import UrlFetcherRomanticTimesReviewersChoiceRomance
from .lambda_literary_awards import UrlFetcherLambdaLiteraryAwardsRomance
from .romance_writers_australia import UrlFetcherRomanceWritersAustraliaRubyAwards
from .australian_romance_readers import UrlFetcherAustralianRomanceReadersAwards
from .holt_medallion import UrlFetcherHOLTMedallion
from .booksellers_best import UrlFetcherBooksellersBestAward
from .goodreads_choice_awards import (
  UrlFetcherGoodreadsChoiceAwardsAudiobook,
  UrlFetcherGoodreadsChoiceAwardsBestBook,
  UrlFetcherGoodreadsChoiceAwardsBestOfTheBest,
  UrlFetcherGoodreadsChoiceAwardsBusiness,
  UrlFetcherGoodreadsChoiceAwardsChickLit,
  UrlFetcherGoodreadsChoiceAwardsChildrensMiddleGrade,
  UrlFetcherGoodreadsChoiceAwardsDebutNovel,
  UrlFetcherGoodreadsChoiceAwardsFantasy,
  UrlFetcherGoodreadsChoiceAwardsFiction,
  UrlFetcherGoodreadsChoiceAwardsFoodCooking,
  UrlFetcherGoodreadsChoiceAwardsGraphicNovelsComics,
  UrlFetcherGoodreadsChoiceAwardsHistoricalFiction,
  UrlFetcherGoodreadsChoiceAwardsHistoryBiography,
  UrlFetcherGoodreadsChoiceAwardsHorror,
  UrlFetcherGoodreadsChoiceAwardsHumor,
  UrlFetcherGoodreadsChoiceAwardsMemoir,
  UrlFetcherGoodreadsChoiceAwardsMysteryThriller,
  UrlFetcherGoodreadsChoiceAwardsNonfiction,
  UrlFetcherGoodreadsChoiceAwardsParanormalFantasy,
  UrlFetcherGoodreadsChoiceAwardsPictureBook,
  UrlFetcherGoodreadsChoiceAwardsPoetry,
  UrlFetcherGoodreadsChoiceAwardsRomance,
  UrlFetcherGoodreadsChoiceAwardsRomantasy,
  UrlFetcherGoodreadsChoiceAwardsScienceFiction,
  UrlFetcherGoodreadsChoiceAwardsScienceTechnology,
  UrlFetcherGoodreadsChoiceAwardsTravelOutdoors,
  UrlFetcherGoodreadsChoiceAwardsYoungAdultFantasyScienceFiction,
  UrlFetcherGoodreadsChoiceAwardsYoungAdultFiction,
  UrlFetcherGoodreadsChoiceAwardsYoungAdultSeries,
)
from .morris import UrlFetcherWilliamCMorrisAward
from .yalsa_nonfiction import UrlFetcherYALSAExcellenceNonfictionYoungAdults
from .printz import UrlFetcherMichaelLPrintzAward
from .carnegie_medal import UrlFetcherCarnegieMedalForWriting
from .newbery import UrlFetcherJohnNewberyMedal
from .cbca_book_of_the_year import (
  UrlFetcherCBCABookOfTheYearEarlyChildhood,
  UrlFetcherCBCABookOfTheYearEvePownall,
  UrlFetcherCBCABookOfTheYearMiddleReaders,
  UrlFetcherCBCABookOfTheYearNewIllustrator,
  UrlFetcherCBCABookOfTheYearOlderReaders,
  UrlFetcherCBCABookOfTheYearPictureBook,
  UrlFetcherCBCABookOfTheYearYoungerReaders,
)
from .prime_ministers_literary_awards import (
  UrlFetcherPrimeMinistersLiteraryAwardsAustralianHistory,
  UrlFetcherPrimeMinistersLiteraryAwardsChildrensLiterature,
  UrlFetcherPrimeMinistersLiteraryAwardsFiction,
  UrlFetcherPrimeMinistersLiteraryAwardsNonfiction,
  UrlFetcherPrimeMinistersLiteraryAwardsYoungAdultLiterature,
)
from .stella import UrlFetcherStellaPrize
from .victorian_premiers_literary_awards import (
  UrlFetcherVictorianPremiersLiteraryAwardsChildrensLiterature,
  UrlFetcherVictorianPremiersLiteraryAwardsFiction,
  UrlFetcherVictorianPremiersLiteraryAwardsIndigenousWriting,
  UrlFetcherVictorianPremiersLiteraryAwardsNonfiction,
  UrlFetcherVictorianPremiersLiteraryAwardsWritingForYoungAdults,
)
from .writers_trust import (
  UrlFetcherWritersTrustAtwoodGibsonFiction,
  UrlFetcherWritersTrustBalsilliePublicPolicy,
  UrlFetcherWritersTrustHilaryWestonNonfiction,
  UrlFetcherWritersTrustShaughnessyCohenPoliticalWriting,
)
from .seiun import UrlFetcherSeiunTranslatedNovel
from .seiun import (
  UrlFetcherSeiunComic,
  UrlFetcherSeiunJapaneseLongWork,
  UrlFetcherSeiunNonfiction,
)
from .sword_and_laser import UrlFetcherSwordAndLaser
from .aurora import (
  UrlFetcherAuroraGraphicNovel,
  UrlFetcherAuroraNoveletteNovella,
  UrlFetcherAuroraNovel,
  UrlFetcherAuroraRelatedWork,
  UrlFetcherAuroraYANovel,
)
from .aurealis import (
  UrlFetcherAurealisAnthology,
  UrlFetcherAurealisChildrens812IllustratedWorkPictureBook,
  UrlFetcherAurealisChildrens812LongFiction,
  UrlFetcherAurealisChildrensBook,
  UrlFetcherAurealisChildrensFiction,
  UrlFetcherAurealisChildrensFictionPictures,
  UrlFetcherAurealisChildrensFictionWords,
  UrlFetcherAurealisCollection,
  UrlFetcherAurealisFantasyNovel,
  UrlFetcherAurealisFantasyNovella,
  UrlFetcherAurealisGoldenAurealisNovel,
  UrlFetcherAurealisGraphicNovelIllustratedWork,
  UrlFetcherAurealisHorrorNovel,
  UrlFetcherAurealisHorrorNovella,
  UrlFetcherAurealisSaraDouglassBookSeries,
  UrlFetcherAurealisSFNovel,
  UrlFetcherAurealisSFNovella,
  UrlFetcherAurealisYoungAdultNovel,
)
from .bram_stoker import (
  UrlFetcherBramStokerAnthology,
  UrlFetcherBramStokerFictionCollection,
  UrlFetcherBramStokerFirstNovel,
  UrlFetcherBramStokerLongFiction,
  UrlFetcherBramStokerMiddleGradeNovel,
  UrlFetcherBramStokerNonfiction,
  UrlFetcherBramStokerNovel,
  UrlFetcherBramStokerGraphicNovel,
  UrlFetcherBramStokerPoetryCollection,
  UrlFetcherBramStokerYoungAdultNovel,
)
from .bsfa import (
  UrlFetcherBSFACollectionAnthology,
  UrlFetcherBSFAFictionForYoungerReaders,
  UrlFetcherBSFALongNonfiction,
  UrlFetcherBSFANovel,
  UrlFetcherBSFAShorterFiction,
)
from .clarke import UrlFetcherArthurCClarkeAwardNovel
from .cwa import (
  UrlFetcherCWACrimeFictionInTranslationDagger,
  UrlFetcherCWAGoldDagger,
  UrlFetcherCWAHistoricalDagger,
  UrlFetcherCWAIanFlemingSteelDagger,
)
from .edgar import (
  UrlFetcherEdgarCriticalBiographicalWork,
  UrlFetcherEdgarFactCrime,
  UrlFetcherEdgarFirstNovel,
  UrlFetcherEdgarJuvenile,
  UrlFetcherEdgarLilianJacksonBraunAward,
  UrlFetcherEdgarMaryHigginsClarkAward,
  UrlFetcherEdgarNovel,
  UrlFetcherEdgarPaperbackOriginal,
  UrlFetcherEdgarYoungAdult,
)
from .itw import (
  UrlFetcherITWBestAudiobook,
  UrlFetcherITWBestEBookOriginalNovel,
  UrlFetcherITWBestFirstNovel,
  UrlFetcherITWBestHardcoverNovel,
  UrlFetcherITWBestPaperbackOriginalNovel,
  UrlFetcherITWBestSeriesNovel,
  UrlFetcherITWBestStandaloneMysteryNovel,
  UrlFetcherITWBestStandaloneThrillerNovel,
  UrlFetcherITWBestYoungAdultNovel,
)
from .ditmar import (
  UrlFetcherDitmarCollectedWork,
  UrlFetcherDitmarNovel,
  UrlFetcherDitmarNovellaNovelette,
)
from .hugo import (
  UrlFetcherHugoAwardsGraphicStory,
  UrlFetcherHugoAwardsNovel,
  UrlFetcherHugoAwardsNovella,
  UrlFetcherHugoAwardsRelatedWork,
  UrlFetcherHugoAwardsSeries,
  UrlFetcherLodestarAward,
)
from .locus import (
  UrlFetcherLocusAllTime1975Novel,
  UrlFetcherLocusAllTime1987FantasyNovel,
  UrlFetcherLocusAllTime1987SFNovel,
  UrlFetcherLocusAllTime1998FantasyNovel,
  UrlFetcherLocusAllTime1998SFNovel,
  UrlFetcherLocusAllTime2012FH20thNovel,
  UrlFetcherLocusAllTime2012FH21stNovel,
  UrlFetcherLocusAllTime2012SF20thNovel,
  UrlFetcherLocusAllTime2012SF21stNovel,
  UrlFetcherLocusAnnualFantasyNovel,
  UrlFetcherLocusAnnualFirstNovel,
  UrlFetcherLocusAnnualHorrorNovel,
  UrlFetcherLocusAnnualAnthology,
  UrlFetcherLocusAnnualCollection,
  UrlFetcherLocusAnnualIllustratedAndArtBook,
  UrlFetcherLocusAnnualNonfiction,
  UrlFetcherLocusAnnualNovella,
  UrlFetcherLocusAnnualSFNovel,
  UrlFetcherLocusAnnualTranslatedNovel,
  UrlFetcherLocusAnnualYoungAdultNovel,
)
from .mythopoeic import (
  UrlFetcherMythopoeicAdultLiterature,
  UrlFetcherMythopoeicChildrensLiterature,
  UrlFetcherMythopoeicFantasy,
  UrlFetcherMythopoeicYoungAdultLiterature,
)
from .nebula import (
  UrlFetcherNebulaAndreNorton,
  UrlFetcherNebulaAwardsComics,
  UrlFetcherNebulaAwardsNovel,
  UrlFetcherNebulaAwardsNovella,
)
from .nommo import (
  UrlFetcherNommoGraphicNovel,
  UrlFetcherNommoNovel,
  UrlFetcherNommoNovella,
)
from .otherwise_tiptree import UrlFetcherOtherwiseTiptreeBooksAndSeries
from .philip_k_dick import UrlFetcherPhilipKDickAwardNovel
from .prometheus import (
  UrlFetcherPrometheusHallOfFame,
  UrlFetcherPrometheusNovel,
  UrlFetcherPrometheusSpecialAwards,
  UrlFetcherPrometheusYoungAdultHonorRoll,
)
from .shirley_jackson import (
  UrlFetcherShirleyJacksonEditedAnthology,
  UrlFetcherShirleyJacksonNovel,
  UrlFetcherShirleyJacksonNovella,
  UrlFetcherShirleyJacksonSingleAuthorCollection,
)
from .spsfc import UrlFetcherSPSFCNovelFinalists
from .world_fantasy import (
  UrlFetcherWorldFantasyAnthology,
  UrlFetcherWorldFantasyCollection,
  UrlFetcherWorldFantasyCollectionAnthology,
  UrlFetcherWorldFantasyNovel,
  UrlFetcherWorldFantasyNovella,
)
from .british_fantasy import (
  UrlFetcherBritishFantasyAnthology,
  UrlFetcherBritishFantasyBestNovel,
  UrlFetcherBritishFantasyCollection,
  UrlFetcherBritishFantasyFantasyNovel,
  UrlFetcherBritishFantasyHorrorNovel,
  UrlFetcherBritishFantasyNonfiction,
  UrlFetcherBritishFantasyNovella,
)
from .international_horror_guild import (
  UrlFetcherInternationalHorrorGuildAnthology,
  UrlFetcherInternationalHorrorGuildCollection,
  UrlFetcherInternationalHorrorGuildFirstNovel,
  UrlFetcherInternationalHorrorGuildIllustratedNarrative,
  UrlFetcherInternationalHorrorGuildLongFiction,
  UrlFetcherInternationalHorrorGuildMidLengthFiction,
  UrlFetcherInternationalHorrorGuildNonfiction,
  UrlFetcherInternationalHorrorGuildNovel,
)
from .australasian_shadows import (
  UrlFetcherAustralasianShadowsCollectedWork,
  UrlFetcherAustralasianShadowsEditedWork,
  UrlFetcherAustralasianShadowsGraphicNovel,
  UrlFetcherAustralasianShadowsLongFiction,
  UrlFetcherAustralasianShadowsNonfiction,
  UrlFetcherAustralasianShadowsNovel,
)
from .this_is_horror import (
  UrlFetcherThisIsHorrorAnthology,
  UrlFetcherThisIsHorrorNovel,
  UrlFetcherThisIsHorrorNovella,
  UrlFetcherThisIsHorrorShortStoryCollection,
)
from .splatterpunk import (
  UrlFetcherSplatterpunkAnthology,
  UrlFetcherSplatterpunkCollection,
  UrlFetcherSplatterpunkNovel,
  UrlFetcherSplatterpunkNovella,
)
from .ladies_of_horror_fiction import (
  UrlFetcherLadiesOfHorrorFictionCollection,
  UrlFetcherLadiesOfHorrorFictionDebut,
  UrlFetcherLadiesOfHorrorFictionGraphicNovel,
  UrlFetcherLadiesOfHorrorFictionMiddleGrade,
  UrlFetcherLadiesOfHorrorFictionNovel,
  UrlFetcherLadiesOfHorrorFictionNovella,
  UrlFetcherLadiesOfHorrorFictionPoetryCollection,
  UrlFetcherLadiesOfHorrorFictionYoungAdult,
)


URL_FETCHER_CLASSES = (
  UrlFetcherRFantasyTopNovels2025,
  UrlFetcherRFantasyTopStandaloneNovels2024,
  UrlFetcherRFantasyTopSelfPublishedNovels2024,
  UrlFetcherSwordAndLaser,
  UrlFetcherHugoAwardsNovel,
  UrlFetcherHugoAwardsNovella,
  UrlFetcherHugoAwardsSeries,
  UrlFetcherHugoAwardsGraphicStory,
  UrlFetcherHugoAwardsRelatedWork,
  UrlFetcherLodestarAward,
  UrlFetcherNebulaAwardsNovel,
  UrlFetcherNebulaAwardsNovella,
  UrlFetcherNebulaAndreNorton,
  UrlFetcherNebulaAwardsComics,
  UrlFetcherLocusAnnualSFNovel,
  UrlFetcherLocusAnnualFantasyNovel,
  UrlFetcherLocusAnnualHorrorNovel,
  UrlFetcherLocusAnnualYoungAdultNovel,
  UrlFetcherLocusAnnualFirstNovel,
  UrlFetcherLocusAnnualTranslatedNovel,
  UrlFetcherLocusAnnualNovella,
  UrlFetcherLocusAnnualAnthology,
  UrlFetcherLocusAnnualCollection,
  UrlFetcherLocusAnnualNonfiction,
  UrlFetcherLocusAnnualIllustratedAndArtBook,
  UrlFetcherLocusAllTime1975Novel,
  UrlFetcherLocusAllTime1987SFNovel,
  UrlFetcherLocusAllTime1987FantasyNovel,
  UrlFetcherLocusAllTime1998SFNovel,
  UrlFetcherLocusAllTime1998FantasyNovel,
  UrlFetcherLocusAllTime2012SF20thNovel,
  UrlFetcherLocusAllTime2012FH20thNovel,
  UrlFetcherLocusAllTime2012SF21stNovel,
  UrlFetcherLocusAllTime2012FH21stNovel,
  UrlFetcherWorldFantasyNovel,
  UrlFetcherWorldFantasyNovella,
  UrlFetcherWorldFantasyAnthology,
  UrlFetcherWorldFantasyCollection,
  UrlFetcherWorldFantasyCollectionAnthology,
  UrlFetcherBritishFantasyHorrorNovel,
  UrlFetcherBritishFantasyFantasyNovel,
  UrlFetcherBritishFantasyBestNovel,
  UrlFetcherBritishFantasyNovella,
  UrlFetcherBritishFantasyAnthology,
  UrlFetcherBritishFantasyCollection,
  UrlFetcherBritishFantasyNonfiction,
  UrlFetcherInternationalHorrorGuildNovel,
  UrlFetcherInternationalHorrorGuildFirstNovel,
  UrlFetcherInternationalHorrorGuildLongFiction,
  UrlFetcherInternationalHorrorGuildMidLengthFiction,
  UrlFetcherInternationalHorrorGuildCollection,
  UrlFetcherInternationalHorrorGuildAnthology,
  UrlFetcherInternationalHorrorGuildNonfiction,
  UrlFetcherInternationalHorrorGuildIllustratedNarrative,
  UrlFetcherAustralasianShadowsNovel,
  UrlFetcherAustralasianShadowsLongFiction,
  UrlFetcherAustralasianShadowsCollectedWork,
  UrlFetcherAustralasianShadowsEditedWork,
  UrlFetcherAustralasianShadowsGraphicNovel,
  UrlFetcherAustralasianShadowsNonfiction,
  UrlFetcherThisIsHorrorNovel,
  UrlFetcherThisIsHorrorNovella,
  UrlFetcherThisIsHorrorShortStoryCollection,
  UrlFetcherThisIsHorrorAnthology,
  UrlFetcherSplatterpunkNovel,
  UrlFetcherSplatterpunkNovella,
  UrlFetcherSplatterpunkCollection,
  UrlFetcherSplatterpunkAnthology,
  UrlFetcherLadiesOfHorrorFictionNovel,
  UrlFetcherLadiesOfHorrorFictionNovella,
  UrlFetcherLadiesOfHorrorFictionCollection,
  UrlFetcherLadiesOfHorrorFictionDebut,
  UrlFetcherLadiesOfHorrorFictionYoungAdult,
  UrlFetcherLadiesOfHorrorFictionMiddleGrade,
  UrlFetcherLadiesOfHorrorFictionPoetryCollection,
  UrlFetcherLadiesOfHorrorFictionGraphicNovel,
  UrlFetcherArthurCClarkeAwardNovel,
  UrlFetcherBSFANovel,
  UrlFetcherBSFAShorterFiction,
  UrlFetcherBSFACollectionAnthology,
  UrlFetcherBSFAFictionForYoungerReaders,
  UrlFetcherBSFALongNonfiction,
  UrlFetcherPhilipKDickAwardNovel,
  UrlFetcherMythopoeicFantasy,
  UrlFetcherMythopoeicAdultLiterature,
  UrlFetcherMythopoeicYoungAdultLiterature,
  UrlFetcherMythopoeicChildrensLiterature,
  UrlFetcherBramStokerNovel,
  UrlFetcherBramStokerFirstNovel,
  UrlFetcherBramStokerYoungAdultNovel,
  UrlFetcherBramStokerMiddleGradeNovel,
  UrlFetcherBramStokerLongFiction,
  UrlFetcherBramStokerFictionCollection,
  UrlFetcherBramStokerAnthology,
  UrlFetcherBramStokerPoetryCollection,
  UrlFetcherBramStokerGraphicNovel,
  UrlFetcherBramStokerNonfiction,
  UrlFetcherShirleyJacksonNovel,
  UrlFetcherShirleyJacksonNovella,
  UrlFetcherShirleyJacksonSingleAuthorCollection,
  UrlFetcherShirleyJacksonEditedAnthology,
  UrlFetcherOtherwiseTiptreeBooksAndSeries,
  UrlFetcherPrometheusNovel,
  UrlFetcherPrometheusHallOfFame,
  UrlFetcherPrometheusYoungAdultHonorRoll,
  UrlFetcherPrometheusSpecialAwards,
  UrlFetcherAuroraNovel,
  UrlFetcherAuroraYANovel,
  UrlFetcherAuroraNoveletteNovella,
  UrlFetcherAuroraRelatedWork,
  UrlFetcherAuroraGraphicNovel,
  UrlFetcherAurealisSFNovel,
  UrlFetcherAurealisGoldenAurealisNovel,
  UrlFetcherAurealisFantasyNovel,
  UrlFetcherAurealisHorrorNovel,
  UrlFetcherAurealisSFNovella,
  UrlFetcherAurealisFantasyNovella,
  UrlFetcherAurealisHorrorNovella,
  UrlFetcherAurealisAnthology,
  UrlFetcherAurealisCollection,
  UrlFetcherAurealisGraphicNovelIllustratedWork,
  UrlFetcherAurealisYoungAdultNovel,
  UrlFetcherAurealisChildrensBook,
  UrlFetcherAurealisChildrensFiction,
  UrlFetcherAurealisChildrensFictionWords,
  UrlFetcherAurealisChildrensFictionPictures,
  UrlFetcherAurealisChildrens812LongFiction,
  UrlFetcherAurealisChildrens812IllustratedWorkPictureBook,
  UrlFetcherAurealisSaraDouglassBookSeries,
  UrlFetcherDitmarNovel,
  UrlFetcherDitmarNovellaNovelette,
  UrlFetcherDitmarCollectedWork,
  UrlFetcherSPSFCNovelFinalists,
  UrlFetcherSeiunTranslatedNovel,
  UrlFetcherSeiunJapaneseLongWork,
  UrlFetcherSeiunComic,
  UrlFetcherSeiunNonfiction,
  UrlFetcherNommoNovel,
  UrlFetcherNommoNovella,
  UrlFetcherNommoGraphicNovel,
  UrlFetcherEdgarNovel,
  UrlFetcherEdgarFirstNovel,
  UrlFetcherEdgarPaperbackOriginal,
  UrlFetcherEdgarFactCrime,
  UrlFetcherEdgarCriticalBiographicalWork,
  UrlFetcherEdgarJuvenile,
  UrlFetcherEdgarYoungAdult,
  UrlFetcherEdgarMaryHigginsClarkAward,
  UrlFetcherEdgarLilianJacksonBraunAward,
  UrlFetcherCWAGoldDagger,
  UrlFetcherCWAIanFlemingSteelDagger,
  UrlFetcherCWAHistoricalDagger,
  UrlFetcherCWACrimeFictionInTranslationDagger,
  UrlFetcherITWBestStandaloneThrillerNovel,
  UrlFetcherITWBestStandaloneMysteryNovel,
  UrlFetcherITWBestSeriesNovel,
  UrlFetcherITWBestFirstNovel,
  UrlFetcherITWBestYoungAdultNovel,
  UrlFetcherITWBestHardcoverNovel,
  UrlFetcherITWBestPaperbackOriginalNovel,
  UrlFetcherITWBestEBookOriginalNovel,
  UrlFetcherITWBestAudiobook,
  UrlFetcherAnthonyAnthologyCollection,
  UrlFetcherAgathaBestNovel,
  UrlFetcherAgathaFirstNovel,
  UrlFetcherAgathaHistoricalNovel,
  UrlFetcherAgathaNonFiction,
  UrlFetcherAgathaChildrensYA,
  UrlFetcherMacavityMysteryNovel,
  UrlFetcherMacavityFirstMystery,
  UrlFetcherMacavityHistoricalMystery,
  UrlFetcherMacavityNonfictionCritical,
  UrlFetcherShamusPINovel,
  UrlFetcherShamusPaperbackOriginal,
  UrlFetcherShamusFirstPINovel,
  UrlFetcherBarryMysteryNovel,
  UrlFetcherBarryFirstMysteryNovel,
  UrlFetcherBarryPaperbackOriginal,
  UrlFetcherBarryThriller,
  UrlFetcherBarryBritishCrimeNovel,
  UrlFetcherHammettPrize,
  UrlFetcherNeroAward,
  UrlFetcherStrandMysteryNovel,
  UrlFetcherStrandDebutMystery,
  UrlFetcherCrimeWritersOfCanadaNovel,
  UrlFetcherCrimeWritersOfCanadaFirstNovel,
  UrlFetcherCrimeWritersOfCanadaNonfiction,
  UrlFetcherCrimeWritersOfCanadaJuvenileYA,
  UrlFetcherCrimeWritersOfCanadaFrenchCrimeBook,
  UrlFetcherDavittAdultNovel,
  UrlFetcherDavittDebutNovel,
  UrlFetcherDavittNonFiction,
  UrlFetcherDavittYoungAdultNovel,
  UrlFetcherDavittChildrensNovel,
  UrlFetcherDilysAward,
  UrlFetcherGumshoeMystery,
  UrlFetcherGumshoeThriller,
  UrlFetcherGumshoeFirstNovel,
  UrlFetcherGumshoeEuropeanCrimeNovel,
  UrlFetcherLeftyHumorousMysteryNovel,
  UrlFetcherLeftyHistoricalMysteryNovel,
  UrlFetcherLeftyMysteryNovel,
  UrlFetcherLeftyDebutMysteryNovel,
  UrlFetcherNedKellyCrimeFiction,
  UrlFetcherNedKellyDebutCrimeFiction,
  UrlFetcherNedKellyTrueCrime,
  UrlFetcherNedKellyInternationalCrimeFiction,
  UrlFetcherNgaioMarshCrimeNovel,
  UrlFetcherNgaioMarshFirstNovel,
  UrlFetcherNgaioMarshNonFiction,
  UrlFetcherNgaioMarshYoungerReaders,
  UrlFetcherTheakstonOldPeculierCrimeNovelOfTheYear,
  UrlFetcherPulitzerFiction,
  UrlFetcherPulitzerGeneralNonfiction,
  UrlFetcherNationalBookAwardFiction,
  UrlFetcherNationalBookAwardNonfiction,
  UrlFetcherNationalBookAwardYoungPeoplesLiterature,
  UrlFetcherBaillieGiffordPrize,
  UrlFetcherPENGalbraithAward,
  UrlFetcherPENDiamonsteinSpielvogelAward,
  UrlFetcherPENJeanSteinBookAward,
  UrlFetcherPENOpenBookAward,
  UrlFetcherPENFaulknerAward,
  UrlFetcherPENHemingwayAward,
  UrlFetcherJAnthonyLukasBookPrize,
  UrlFetcherMarkLyntonHistoryPrize,
  UrlFetcherOrwellPrizePoliticalWriting,
  UrlFetcherAndrewCarnegieNonfiction,
  UrlFetcherKirkusPrizeFiction,
  UrlFetcherKirkusPrizeNonfiction,
  UrlFetcherKirkusPrizeYoungReadersLiterature,
  UrlFetcherWomensPrizeNonFiction,
  UrlFetcherWomensPrizeFiction,
  UrlFetcherRoyalSocietyScienceBookPrize,
  UrlFetcherBookerPrize,
  UrlFetcherInternationalBookerPrize,
  UrlFetcherGovernorGeneralEnglishFiction,
  UrlFetcherGovernorGeneralEnglishNonfiction,
  UrlFetcherGovernorGeneralEnglishYoungPeoplesText,
  UrlFetcherGovernorGeneralEnglishYoungPeoplesIllustratedBooks,
  UrlFetcherGovernorGeneralFrenchYoungPeoplesText,
  UrlFetcherGovernorGeneralFrenchYoungPeoplesIllustratedBooks,
  UrlFetcherCostaWhitbreadNovel,
  UrlFetcherCostaWhitbreadFirstNovel,
  UrlFetcherCostaWhitbreadBiography,
  UrlFetcherCostaWhitbreadChildrensBook,
  UrlFetcherCostaWhitbreadBookOfTheYear,
  UrlFetcherGillerPrize,
  UrlFetcherFolioWritersPrizeBookOfTheYear,
  UrlFetcherFolioWritersPrizeFiction,
  UrlFetcherFolioWritersPrizeNonfiction,
  UrlFetcherGoldsmithsPrize,
  UrlFetcherNationalBookCriticsCircleFiction,
  UrlFetcherNationalBookCriticsCircleNonfiction,
  UrlFetcherNationalBookCriticsCircleBiography,
  UrlFetcherNationalBookCriticsCircleMemoirAutobiography,
  UrlFetcherNationalBookCriticsCirclePoetry,
  UrlFetcherNationalBookCriticsCircleCriticism,
  UrlFetcherNationalBookCriticsCircleJohnLeonard,
  UrlFetcherNationalBookCriticsCircleGreggBarriosTranslation,
  UrlFetcherDublinLiteraryAward,
  UrlFetcherCenterForFictionFirstNovelPrize,
  UrlFetcherWalterScottPrize,
  UrlFetcherJamesTaitBlackFiction,
  UrlFetcherJamesTaitBlackBiography,
  UrlFetcherMilesFranklinLiteraryAward,
  UrlFetcherNeroBookAwardsFiction,
  UrlFetcherNeroBookAwardsDebutFiction,
  UrlFetcherNeroBookAwardsNonfiction,
  UrlFetcherNeroBookAwardsChildrensFiction,
  UrlFetcherNeroBookAwardsGoldPrize,
  UrlFetcherStellaPrize,
  UrlFetcherPrimeMinistersLiteraryAwardsFiction,
  UrlFetcherPrimeMinistersLiteraryAwardsNonfiction,
  UrlFetcherPrimeMinistersLiteraryAwardsAustralianHistory,
  UrlFetcherPrimeMinistersLiteraryAwardsYoungAdultLiterature,
  UrlFetcherPrimeMinistersLiteraryAwardsChildrensLiterature,
  UrlFetcherVictorianPremiersLiteraryAwardsFiction,
  UrlFetcherVictorianPremiersLiteraryAwardsNonfiction,
  UrlFetcherVictorianPremiersLiteraryAwardsWritingForYoungAdults,
  UrlFetcherVictorianPremiersLiteraryAwardsChildrensLiterature,
  UrlFetcherVictorianPremiersLiteraryAwardsIndigenousWriting,
  UrlFetcherNSWPremiersLiteraryAwardsChristinaSteadFiction,
  UrlFetcherNSWPremiersLiteraryAwardsDouglasStewartNonfiction,
  UrlFetcherNSWPremiersLiteraryAwardsPatriciaWrightsonChildrens,
  UrlFetcherNSWPremiersLiteraryAwardsEthelTurnerYoungPeople,
  UrlFetcherNSWPremiersLiteraryAwardsIndigenousWriters,
  UrlFetcherNSWPremiersLiteraryAwardsGlendaAdamsNewWriting,
  UrlFetcherNSWPremiersLiteraryAwardsMulticulturalNSW,
  UrlFetcherNSWPremiersLiteraryAwardsBookOfTheYear,
  UrlFetcherNSWPremiersLiteraryAwardsPeoplesChoice,
  UrlFetcherQueenslandLiteraryAwardsStateSignificance,
  UrlFetcherQueenslandLiteraryAwardsFiction,
  UrlFetcherQueenslandLiteraryAwardsNonfiction,
  UrlFetcherQueenslandLiteraryAwardsChildrens,
  UrlFetcherQueenslandLiteraryAwardsYoungAdult,
  UrlFetcherQueenslandLiteraryAwardsPeoplesChoice,
  UrlFetcherWesternAustralianPremiersBookAwardsBookOfTheYear,
  UrlFetcherWesternAustralianPremiersBookAwardsFiction,
  UrlFetcherWesternAustralianPremiersBookAwardsNonfiction,
  UrlFetcherWesternAustralianPremiersBookAwardsEmergingWriter,
  UrlFetcherWesternAustralianPremiersBookAwardsChildrens,
  UrlFetcherWesternAustralianPremiersBookAwardsYoungAdult,
  UrlFetcherSouthAustralianLiteraryAwardsPremiersAward,
  UrlFetcherSouthAustralianLiteraryAwardsFiction,
  UrlFetcherSouthAustralianLiteraryAwardsNonfiction,
  UrlFetcherSouthAustralianLiteraryAwardsChildrens,
  UrlFetcherSouthAustralianLiteraryAwardsYoungAdult,
  UrlFetcherACTBookOfTheYearAward,
  UrlFetcherRWARITAAwards,
  UrlFetcherRWAVivianAwards,
  UrlFetcherRNARomanticNovelAwards,
  UrlFetcherRNAJoanHessayonAward,
  UrlFetcherRippedBodiceAwards,
  UrlFetcherRomanticTimesReviewersChoiceRomance,
  UrlFetcherLambdaLiteraryAwardsRomance,
  UrlFetcherRomanceWritersAustraliaRubyAwards,
  UrlFetcherAustralianRomanceReadersAwards,
  UrlFetcherHOLTMedallion,
  UrlFetcherBooksellersBestAward,
  UrlFetcherGoodreadsChoiceAwardsFiction,
  UrlFetcherGoodreadsChoiceAwardsHistoricalFiction,
  UrlFetcherGoodreadsChoiceAwardsMysteryThriller,
  UrlFetcherGoodreadsChoiceAwardsRomance,
  UrlFetcherGoodreadsChoiceAwardsRomantasy,
  UrlFetcherGoodreadsChoiceAwardsFantasy,
  UrlFetcherGoodreadsChoiceAwardsScienceFiction,
  UrlFetcherGoodreadsChoiceAwardsHorror,
  UrlFetcherGoodreadsChoiceAwardsDebutNovel,
  UrlFetcherGoodreadsChoiceAwardsAudiobook,
  UrlFetcherGoodreadsChoiceAwardsYoungAdultFiction,
  UrlFetcherGoodreadsChoiceAwardsYoungAdultFantasyScienceFiction,
  UrlFetcherGoodreadsChoiceAwardsNonfiction,
  UrlFetcherGoodreadsChoiceAwardsMemoir,
  UrlFetcherGoodreadsChoiceAwardsHistoryBiography,
  UrlFetcherGoodreadsChoiceAwardsYoungAdultSeries,
  UrlFetcherGoodreadsChoiceAwardsChildrensMiddleGrade,
  UrlFetcherGoodreadsChoiceAwardsPictureBook,
  UrlFetcherGoodreadsChoiceAwardsScienceTechnology,
  UrlFetcherGoodreadsChoiceAwardsBusiness,
  UrlFetcherGoodreadsChoiceAwardsFoodCooking,
  UrlFetcherGoodreadsChoiceAwardsTravelOutdoors,
  UrlFetcherGoodreadsChoiceAwardsGraphicNovelsComics,
  UrlFetcherGoodreadsChoiceAwardsPoetry,
  UrlFetcherGoodreadsChoiceAwardsHumor,
  UrlFetcherGoodreadsChoiceAwardsParanormalFantasy,
  UrlFetcherGoodreadsChoiceAwardsChickLit,
  UrlFetcherGoodreadsChoiceAwardsBestBook,
  UrlFetcherGoodreadsChoiceAwardsBestOfTheBest,
  UrlFetcherWilliamCMorrisAward,
  UrlFetcherYALSAExcellenceNonfictionYoungAdults,
  UrlFetcherMichaelLPrintzAward,
  UrlFetcherCarnegieMedalForWriting,
  UrlFetcherJohnNewberyMedal,
  UrlFetcherCBCABookOfTheYearOlderReaders,
  UrlFetcherCBCABookOfTheYearYoungerReaders,
  UrlFetcherCBCABookOfTheYearMiddleReaders,
  UrlFetcherCBCABookOfTheYearEarlyChildhood,
  UrlFetcherCBCABookOfTheYearPictureBook,
  UrlFetcherCBCABookOfTheYearEvePownall,
  UrlFetcherCBCABookOfTheYearNewIllustrator,
  UrlFetcherWritersTrustAtwoodGibsonFiction,
  UrlFetcherWritersTrustHilaryWestonNonfiction,
  UrlFetcherWritersTrustBalsilliePublicPolicy,
  UrlFetcherWritersTrustShaughnessyCohenPoliticalWriting,
  UrlFetcherAnthonyChildrensYA,
  UrlFetcherAnthonyCozyHumorousMystery,
  UrlFetcherAnthonyCriticalNonfictionWork,
  UrlFetcherAnthonyFirstMystery,
  UrlFetcherAnthonyHistoricalMystery,
  UrlFetcherAnthonyMysteryNovel,
  UrlFetcherAnthonyPaperbackEBookAudiobook,
  UrlFetcherAnthonyParanormalMystery,
)


def available_url_fetchers():
  return tuple(fetcher_class() for fetcher_class in URL_FETCHER_CLASSES)
